# generated by datamodel-codegen:
#   filename:  issue_links.json
#   timestamp: 2022-11-10T08:09:52+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, Extra, Field


class Type(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = None
    name: Optional[str] = None
    inward: Optional[str] = None
    outward: Optional[str] = None
    self: Optional[AnyUrl] = None


class StatusCategory(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    id: Optional[int] = None
    key: Optional[str] = None
    colorName: Optional[str] = None
    name: Optional[str] = None


class Status(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    statusColor: Optional[str] = None
    description: Optional[str] = None
    iconUrl: Optional[str] = None
    name: Optional[str] = None
    id: Optional[str] = None
    statusCategory: Optional[StatusCategory] = Field(None, title="Status Category")


class Issuetype(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    id: Optional[str] = None
    description: Optional[str] = None
    iconUrl: Optional[str] = None
    name: Optional[str] = None
    subtask: bool
    avatarId: Optional[int] = None
    hierarchyLevel: Optional[int] = None


class Priority(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    statusColor: Optional[str] = None
    description: Optional[str] = None
    iconUrl: Optional[str] = None
    name: Optional[str] = None
    id: Optional[str] = None


class Fields(BaseModel):
    class Config:
        extra = Extra.forbid

    summary: Optional[str] = None
    status: Optional[Status] = Field(None, title="Status")
    issuetype: Optional[Issuetype] = Field(None, title="Issue Type")
    priority: Optional[Priority] = Field(None, title="Priority")


class IssueRef(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = None
    key: Optional[str] = None
    self: Optional[AnyUrl] = None
    fields: Optional[Fields] = Field(None, title="Fields")


class IssueLink(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = None
    self: Optional[AnyUrl] = None
    type: Optional[Type] = Field(None, title="Issue Link Type")
    inwardIssue: Optional[IssueRef] = None
    outwardIssue: Optional[IssueRef] = None
