# generated by datamodel-codegen:
#   filename:  issue_links.json
#   timestamp: 2022-11-10T08:09:52+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, Extra, Field


class Type(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    name: str
    inward: Optional[str] = None
    outward: Optional[str] = None
    self: Optional[AnyUrl] = None


class StatusCategory(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    id: Optional[int] = None
    key: Optional[str] = None
    colorName: Optional[str] = None
    name: str


class Status(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    statusColor: Optional[str] = None
    description: Optional[str] = None
    iconUrl: Optional[str] = None
    name: Optional[str] = None
    id: Optional[str] = None
    statusCategory: StatusCategory


class Issuetype(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    id: Optional[str] = None
    description: Optional[str] = None
    iconUrl: Optional[str] = None
    name: Optional[str] = None
    subtask: bool
    avatarId: Optional[int] = None
    hierarchyLevel: Optional[int] = None


class Priority(BaseModel):
    class Config:
        extra = Extra.forbid

    self: Optional[str] = None
    statusColor: Optional[str] = None
    description: Optional[str] = None
    iconUrl: Optional[str] = None
    name: Optional[str] = None
    id: Optional[str] = None


class Fields(BaseModel):
    class Config:
        extra = Extra.forbid

    summary: str
    status: Status
    priority: Optional[Priority] = Field(None, title="Priority")
    issuetype: Optional[Issuetype] = Field(None, title="Issue Type")


class IssueRef(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    key: str
    self: Optional[AnyUrl] = None
    fields: Fields


class IssueLink(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = None
    self: Optional[AnyUrl] = None
    type: Type
    inwardIssue: Optional[IssueRef] = None
    outwardIssue: Optional[IssueRef] = None
